spring:
  datasource:
    username: root    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotelmanagement
      jpa:    show-sql: true
    hibernate:      ddl-auto: update   
server:  port: 9090
      
      
      